### ISSUE TITLE
No separate channel outputs

### ISSUE THREAD

**Issue by lvd2** [jotego/jt49#4]
There is a summed sound levels output at '[9:0] sound' pins. However, separate channel's outputs (A, B, C) are now unconnected.
 
In the environments where YM2149 generates mono sound, this is OK and just what expected. However, the majority of ZX Spectrum clones do separate YM channels like this: channel A is left, channel C is right, channel B is middle (i.e. mixed into both left and right stereo signals). Currently jt49 is unusable in stereo configurations like those.

**Comment by jotego** [comment]
I don't understand. Separated outputs are available for both the embedded jt49.v version and the standalone jt49_bus.v one.

**Comment by lvd2** [comment]
I look into jt49.v.
`output reg [9:0] sound` is assigned to some value inside some of always blocks.
However, neither of `output [7:0] A`,  `output [7:0] B` or  `output [7:0] C` is assigned anywhere inside the module.

**Comment by jotego** [comment]
I have connected the ports. Please ensure to use a clock enable signal different from a permanent 1.
