### ISSUE TITLE
no envelope generated sound

### ISSUE THREAD

**Issue by LMN128** [jotego/jt49#6]
I have a problem with last commit in compare with 954bfeed1d813d21510e48ab454eb56b6a7ab2bf which is OK. There is no envelope sound. I use it together with jt03 (YM2203). I have noticed jt12 has different source code of jt49 than than this repository.

**Comment by jotego** [comment]
Hi, jt12 does refer to the latest commit which has no EG problems:
https://github.com/jotego/jt49/commit/57619f8b06487454d8a7e345590fcce4c14e6fc4
Please be sure to be using JT12 from my repository and not some fork. Please use `git submodule update` to correctly update submodules. git pull in the master directory will not update submodules.

**Comment by LMN128** [comment]
Hi, sorry for git confusion, i was bad.
But, my jt03 implementation still not work. Variable volume control doesn't work in this commit.
it works well in 954bfeed1d813d21510e48ab454eb56b6a7ab2bf.
Thanks a lot.

**Comment by jotego** [comment]
Hi, I just resimulated it. I do not see any problem with variable volume control. Are you setting a permanent one on the clock enable input. The README file clearly states you are not supposed to do that.
Please review your simulations.

**Comment by LMN128** [comment]
Hi, I suppouse ce is right:
clk is 56MHz and ce is:
```
logic ce_ay;
logic [3:0] ay_clk_counter; 
always_ff @ (posedge clk56)
begin 
 ay_clk_counter++;
 ce_ay <= !ay_clk_counter;
end
```

**Comment by jotego** [comment]
Sorry but this is meant to be about issues in the JT49 core itself. If you want support about your code consider joining [Patreon](https://www.patreon.com/topapate) on one of the high tiers.
